In [2]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")
products = pd.read_csv("../data/raw/products.csv")
orders = pd.read_csv("../data/raw/orders.csv")
payments = pd.read_csv("../data/raw/payments.csv")

In [3]:
customers.head()

,customer_id,name,email,city,state,age
0,1,Nicholas Thompson,vmccarthy@example.com,Port Vincentmouth,Tennessee,26
1,2,Sandra Stein,rodriguezlarry@example.net,West Oscarburgh,New York,38
2,3,Joseph Kelly,monroechad@example.org,Port Jenniferville,West Virginia,50
3,4,Krystal Jackson,carol63@example.org,Port Dwayneton,Pennsylvania,32
4,5,Zachary Gomez,lflores@example.com,New Kyle,New Jersey,19

In [4]:
products.head()

   product_id product_name     category     price
0           1          Bad        Books  69835.07
1           2        Force  Electronics  42008.40
2           3        Total  Electronics  38620.35
3           4           Mr     Clothing  71206.88
4           5          Dog         Home  25065.60

In [5]:
orders.head()

   order_id  customer_id  product_id  quantity  order_date
0         1         8021          81         3  2026-05-26
1         2         9642         532         3  2025-11-03
2         3         9858          99         3  2026-06-22
3         4         8042         788         4  2025-10-12
4         5         2595         787         4  2026-06-21

In [6]:
payments.head()

   payment_id  order_id payment_method payment_status
0           1         1    Net Banking         Failed
1           2         2            UPI        Success
2           3         3           Cash        success
3           4         4    Credit Card        success
4           5         5            UPI         FAILED

In [7]:
print("Customers shape:", customers.shape)
print("Products shape:", products.shape)
print("Orders shape:", orders.shape)
print("Payments shape:", payments.shape)

Customers shape: (10100, 6)
Products shape: (1000, 4)
Orders shape: (50000, 5)
Payments shape: (50000, 4)

In [8]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10100 non-null  int64
 1   name         10100 non-null  str
 2   email        9884 non-null   str
 3   city         10100 non-null  str
 4   state        10100 non-null  str
 5   age          10100 non-null  int64
dtypes: int64(2), str(4)
memory usage: 473.6 KB

In [9]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50000 non-null  int64
 1   customer_id  50000 non-null  int64
 2   product_id   50000 non-null  int64
 3   quantity     50000 non-null  int64
 4   order_date   50000 non-null  str
dtypes: int64(4), str(1)
memory usage: 1.9 MB

In [10]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   payment_id      50000 non-null  int64
 1   order_id        50000 non-null  int64
 2   payment_method  48924 non-null  str
 3   payment_status  50000 non-null  str
dtypes: int64(2), str(2)
memory usage: 1.5 MB

In [11]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1000 non-null   int64
 1   product_name  1000 non-null   str
 2   category      975 non-null    str
 3   price         1000 non-null   float64
dtypes: float64(1), int64(1), str(2)
memory usage: 31.4 KB

In [12]:
print("CUSTOMERS")
print(customers.isnull().sum())

print("\nPRODUCTS")
print(products.isnull().sum())

print("\nORDERS")
print(orders.isnull().sum())

print("\nPAYMENTS")
print(payments.isnull().sum())

CUSTOMERS
customer_id      0
name             0
email          216
city             0
state            0
age              0
dtype: int64

PRODUCTS
product_id       0
product_name     0
category        25
price            0
dtype: int64

ORDERS
order_id       0
customer_id    0
product_id     0
quantity       0
order_date     0
dtype: int64

PAYMENTS
payment_id           0
order_id             0
payment_method    1076
payment_status       0
dtype: int64

In [13]:
print("Customer duplicates:", customers.duplicated().sum())
print("Product duplicates:", products.duplicated().sum())
print("Order duplicates:", orders.duplicated().sum())
print("Payment duplicates:", payments.duplicated().sum())

Customer duplicates: 100
Product duplicates: 0
Order duplicates: 0
Payment duplicates: 0

In [14]:
print("Duplicate Customer IDs:", customers["customer_id"].duplicated().sum())

print("Duplicate Product IDs:", products["product_id"].duplicated().sum())

print("Duplicate Order IDs:", orders["order_id"].duplicated().sum())

print("Duplicate Payment IDs:", payments["payment_id"].duplicated().sum())

Duplicate Customer IDs: 100
Duplicate Product IDs: 0
Duplicate Order IDs: 0
Duplicate Payment IDs: 0

In [15]:
# Invalid customer IDs in orders
invalid_customer_ids = orders[
    ~orders["customer_id"].isin(customers["customer_id"])
]

print("Orders with invalid customer IDs:", len(invalid_customer_ids))


# Invalid product IDs in orders
invalid_product_ids = orders[
    ~orders["product_id"].isin(products["product_id"])
]

print("Orders with invalid product IDs:", len(invalid_product_ids))


# Invalid order IDs in payments
invalid_order_ids = payments[
    ~payments["order_id"].isin(orders["order_id"])
]

print("Payments with invalid order IDs:", len(invalid_order_ids))

Orders with invalid customer IDs: 498
Orders with invalid product IDs: 508
Payments with invalid order IDs: 0

In [16]:
# Negative or zero product prices
invalid_prices = products[products["price"] <= 0]

print("Products with invalid prices:", len(invalid_prices))


# Missing product categories
print(
    "Products with missing categories:",
    products["category"].isnull().sum()
)


# Invalid order quantities
invalid_quantities = orders[orders["quantity"] <= 0]

print(
    "Orders with invalid quantities:",
    len(invalid_quantities)
)


# Missing customer emails
print(
    "Customers with missing emails:",
    customers["email"].isnull().sum()
)


# Missing payment methods
print(
    "Payments with missing payment methods:",
    payments["payment_method"].isnull().sum()
)

Products with invalid prices: 16
Products with missing categories: 25
Orders with invalid quantities: 510
Customers with missing emails: 216
Payments with missing payment methods: 1076

In [17]:
# Negative or zero product prices
invalid_prices = products[products["price"] <= 0]

print("Products with invalid prices:", len(invalid_prices))


# Missing product categories
print(
    "Products with missing categories:",
    products["category"].isnull().sum()
)


# Invalid order quantities
invalid_quantities = orders[orders["quantity"] <= 0]

print(
    "Orders with invalid quantities:",
    len(invalid_quantities)
)


# Missing customer emails
print(
    "Customers with missing emails:",
    customers["email"].isnull().sum()
)


# Missing payment methods
print(
    "Payments with missing payment methods:",
    payments["payment_method"].isnull().sum()
)

Products with invalid prices: 16
Products with missing categories: 25
Orders with invalid quantities: 510
Customers with missing emails: 216
Payments with missing payment methods: 1076

In [19]:
print(payments["payment_status"].value_counts())

payment_status
Success    25050
success     8464
Failed      8280
FAILED      8206
Name: count, dtype: int64

In [20]:
print(products["category"].value_counts(dropna=False))

category
Sports         211
Electronics    205
Home           194
Clothing       190
Books          175
NaN             25
Name: count, dtype: int64

In [21]:
print(customers["city"].value_counts().head(20))

city
West Michael      11
Port Jennifer     11
New Michael       10
East Michael      10
North Michael     10
Lake Michael      10
New David         10
North Robert      10
Michaelmouth       9
North John         9
South Michelle     8
Lake David         8
Lake John          8
Port Mary          8
West Jason         8
South John         8
Michaelchester     7
New Brian          7
Millerstad         7
North Matthew      7
Name: count, dtype: int64

In [22]:
customers["city_normalized"] = customers["city"].str.lower().str.strip()

print("Unique cities before normalization:", customers["city"].nunique())
print("Unique cities after normalization:", customers["city_normalized"].nunique())

Unique cities before normalization: 7829
Unique cities after normalization: 7730